var hardingsData = 
{
    "salesOrder": {
        "idCompany": 1,
        "idCust": 451526,
        "numTran": 559129,
        "suffixTran": 0,
        "nameCust": "HALL & HART HOMES P/L",
        "custOrderRef": "H0427",
        "idBranch": 57,
        "idBranchOriginal": 57,
        "dateDelivReqd": "2023-02-08",
        "taxable": true,
        "orderTotalInc": 127.27,
        "gstAmount": 11.57,
        "orderTotalExc": 115.7,
        "orderTotalCost": 101.77,
        "orderTotalCostPartRebate": 101.77,
        "orderTotalCostFullRebate": 101.77,
        "orderTotalGrossProfit": 12.0398,
        "orderTotalArea": 0,
        "orderTotalVolume": 34560000,
        "orderTotalWeight": 0,
        "orderVolumeMsg": false,
        "orderWeightMsg": false,
        "settleDisc": 0,
        "totalPaymentAmount": 0,
        "outstandingAmount": 127.27,
        "dateOrd": "2023-02-01",
        "isDateDelivConfirmed": false,
        "dateDelivConfirmed": null,
        "idUser": "master",
        "isConfirmed": false,
        "isOrderSentEtm": false,
        "instructions": "",
        "comment1": "",
        "comment2": "",
        "comment3": "",
        "idPromotion": "",
        "idContract": "",
        "descContract": "",
        "idAssignee": "master",
        "idStatusWrkFlow": "New",
        "numPurchOrd": 0,
        "idProject": 0,
        "descProject": "",
        "idJob": 0,
        "jobName": "",
        "descJob": "",
        "idSection": 0,
        "descSection": "",
        "paymentTermCode": "30EOM",
        "creditStatusMessage": "<font color=\"red\"><b></b></font>",
        "descDeliv": "Q00559129",
        "txtInvoice": null,
        "isSalesmgrChecked": false,
        "isTransportChecked": false,
        "tstat": "o",
        "despatchMethod": "10",
        "despatchMethodDesc": "",
        "isTruePickup": false,
        "deliverToAddress1": "HALL & HART HOMES P/L",
        "deliverToAddress2": "PO BOX 2005",
        "deliverToAddress3": "NORTH PARRAMATTA",
        "deliverToAddress4": "NSW 1750",
        "state": "NSW",
        "postalCode": "1750",
        "addressCust1": "PO BOX 2005",
        "addressCust2": "NORTH PARRAMATTA",
        "addressCust3": "NSW",
        "isGstInc": true,
        "tranType": "qt",
        "tranSubType": "",
        "typeSelect": "qt",
        "idSalesRep": 10,
        "nameSalesRep": "System Administrator",
        "idSalesRepCust": 10,
        "idUserOrRepTakenBy": "master",
        "nameUserOrRepTakenBy": "System Administrator",
        "idUserApproved": "",
        "idSalesZone": "",
        "idDiscGroup": "",
        "refTranExternal": "",
        "diaryType": "order",
        "diaryCode": "00559129 , 00",
        "diarySuffix": "Sales Order 00559129,00",
        "isScannerInput": false,
        "isOrderComplete": false,
        "dateQuote": "2023-02-01",
        "dateQuoteExpiry": "2023-03-03",
        "numTranPlusSuffix": "559129",
        "commentCust": "",
        "notificationCust": "",
        "messageTitle": "",
        "taskLink": "1|451526|559129|0",
        "isTaxExempt": false,
        "isExportSale": false,
        "isOnlineSale": false,
        "statusLock": null,
        "isIntrnlAcct": false,
        "hasLinkedPO": false,
        "isAuthorised": true,
        "commentFreeForm": "",
        "commentQuote01": 0,
        "commentQuote02": 0,
        "commentQuote03": 0,
        "commentQuote04": 0,
        "commentQuote05": 0,
        "commentQuote06": 0,
        "commentQuote07": 0,
        "commentQuote08": 0,
        "commentQuote09": 0,
        "commentQuote10": 0,
        "commentQuote11": 0,
        "commentQuote12": 0,
        "commentQuote13": 0,
        "commentQuote14": 0,
        "commentQuote15": 0,
        "commentQuote16": 0,
        "commentQuote17": 0,
        "commentQuote18": 0,
        "commentQuote19": 0,
        "commentQuote20": 0,
        "isReviewed": false,
        "idUserPricedIntInv": null,
        "commentPrint": "",
        "isInvoicePrinted": false,
        "orderTotalPartRebateGP": 12.0398,
        "orderTotalFullRebateGP": 12.0398,
        "agreedValueEx": 0,
        "pickStatus": "Not started",
        "canClearPick": false,
        "idLoyaltyCard": "",
        "timeTranCreated": 0,
        "hasServicesProduct": false,
        "isBranchTransfer": false,
        "numTimesPslipPrinted": 0,
        "isTradePlus": false,
        "isSpecialBuyIn": false,
        "memberBarcodeExternal": "",
        "hasWorkOrderLines": false,
        "canPick": true,
        "isChargeback": false,
        "idAssemblyLocation": "",
        "dateInterimInvoiceCharge": null,
        "crdBalAmount": 0,
        "custOrderExists": false,
        "dateInvoiced": null,
        "timeInvoiced": 0,
        "idCustContract": 0,
        "idSupp": "",
        "nameSupp": "",
        "isCertifiedUsed": false,
        "linkedTrans": 0,
        "printContext": "",
        "supplierGp": 0,
        "tillNo": 0,
        "idSectionCust": "",
        "idSupplyBranch": "8"
    },
    "salesOrderLine": [
        {
        "idCompany": 1,
        "idCust": 451526,
        "numTran": 559129,
        "suffixTran": 0,
        "numLine": 100,
        "idProd": "6093025",
        "descProd": "Panel Easylap Fibre ",
        "descProd2": "Cement 3600x1200x8.5mm ",
        "descProd3": "404980 JH",
        "descProd4": "",
        "prodDescBrowse": "Panel Easylap Fibre Cement 3600x1200x8.5mm 404980 JH",
        "tranType": "qt",
        "tstat": "o",
        "costUnit": 101.77,
        "costLine": 101.77,
        "qtyTran": 1,
        "qtyTranBrowse": 0,
        "idUom": "EA",
        "globalTxnId": "",
        "multipleUoms": true,
        "qtyNumDecPlaces": 2,
        "pricingMethod": "o",
        "prodGrp": "53",
        "prodSubGrp1": "185",
        "prodSubGrp2": "18500",
        "prodSubGrp3": "0935",
        "taxable": true,
        "unitGst": 11.57,
        "unitSell": 127.27,
        "unitSellBrowse": 0,
        "lineGst": 11.57,
        "lineSell": 127.27,
        "discPerc": 0,
        "discAmount": 0,
        "priceNumDecPlaces": 2,
        "isTally": false,
        "tallyText": "",
        "tallyComment": "",
        "tallyLineSell": 0,
        "priceOverrideReason": "MIG",
        "comment": "",
        "codeUsage": "",
        "descUsage": "",
        "numUsageSeq": "",
        "numUsageSection": 0,
        "idPickingGroup": null,
        "discPriceUnit": 127.27,
        "percRebateSupp": 0,
        "partRebatedUnitCost": 101.77,
        "partRebatedGrossProfit": 12.0398,
        "fullyRebatedUnitCost": 101.77,
        "fullyRebatedGrossProfit": 12.0398,
        "isSuppViaCDF": false,
        "idSupp": "1421",
        "qtyPieces": 0,
        "dateInvoiced": null,
        "dateDeliveryRequired": "2023-02-08",
        "idBranch": 57,
        "idSupplyBranch": 57,
        "idSalesZone": "",
        "idSalesRep": 0,
        "idMajorProductGroup": "",
        "productBrandName": "James Hardie",
        "productLength": 1200,
        "productWidth": 3600,
        "productDepth": 8,
        "codeSpecie": "",
        "unitCostStdNett": 101.77,
        "sellUnitRetail": 157.2727,
        "sellPriceUnit": 127.27,
        "idTimberScheme": "",
        "useTimberScheme": false,
        "userCode": "master",
        "docRef": 34605,
        "tallyType": "",
        "idUomPricing": "EA",
        "idDiscGroup": "",
        "idContract": "",
        "idPromotion": "",
        "sellSurcharge": 0,
        "costSurcharge": 0,
        "grossProfit": 12.0398,
        "refWhouse": "",
        "codeFinish": "",
        "idGrade": "",
        "settlementDiscount": 0,
        "numPack": "",
        "allocatePack": false,
        "pickSlipComment": "",
        "isOrigOrderLine": null,
        "idRebate": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ],
        "percListSuppRebates": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "percRebateReporting": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "numPurchOrd": 0,
        "sufPurchOrd": 0,
        "idTreat": "",
        "idTreat2": "",
        "idTreat3": "",
        "idTreat4": "",
        "surchargeList": ",,,",
        "costUnitTreatment": 0,
        "sellUnitTreatment": 0,
        "idTier": null,
        "isSpecialBuyIn": false,
        "refSuppContract": "",
        "quoteOptionForLine": 0,
        "refCustLine": "",
        "commentInternal": "",
        "willTallyHoldPrice": false,
        "hasFuturePrice": false,
        "isWorkOrderLine": false,
        "pickedQty": 0,
        "backOrdQty": 0,
        "currStockOnHand": 11
        }
    ]
}

var orderLineData = hardingsData['salesOrderLine']

var result = orderLineData.reduce((x, y) => {
    (x[y.idProd] = x[y.idProd] || []).push(y);
    return x;
}, {});

var data = Object.values(result);
var orderLineResult = [];
for(var i = 0; i < data.length; i++)
{
    orderLineResult.push(data[i][0])
    var qtyTran = 0;
    orderLineResult[i].numLine = i+1;
    for(var j = 0; j < data[i].length; j++)
    {
        qtyTran += data[i][j].qtyTran;
    }
    orderLineResult[i].qtyTran = qtyTran;
}
            
hardingsData['salesOrderLine'] = orderLineResult

console.log(orderLineResult)
return hardingsData;